[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }
async-trait = { version = "0.1.89", default-features = false }
thiserror = { version = "2.0.18", default-features = false }
uuid = { version = "1.23.0", features = ["v4", "serde"] }
time = { version = "0.3.47", features = ["serde", "formatting", "parsing"] }
tracing = { version = "0.1.44", default-features = false }
tokio = { version = "1.50.0", features = ["rt-multi-thread", "time", "sync", "signal"] }
rand = { version = "0.10.1", default-features = false, features = ["thread_rng"] }
serde = { version = "1.0.228", features = ["derive"] }

